# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# https://gist.github.com/magnetikonline/6f215db058e327905bce66c37f92426c#file-dependabot-yml
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
